// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheatricalPlayersRefactoringKata.Data;

#nullable disable

namespace TheatricalPlayersRefactoringKata.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240917152752_AddStatement")]
    partial class AddStatement
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.33");

            modelBuilder.Entity("TheatricalPlayersRefactoringKata.Data.Domain.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("TheatricalPlayersRefactoringKata.Data.Domain.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0c3da678-b058-4d7e-bc57-c453e745f5ad"),
                            CreatedAt = new DateTime(2024, 9, 17, 12, 27, 52, 706, DateTimeKind.Local).AddTicks(3877),
                            Name = "comedy",
                            UpdatedAt = new DateTime(2024, 9, 17, 12, 27, 52, 706, DateTimeKind.Local).AddTicks(3893)
                        },
                        new
                        {
                            Id = new Guid("b0728ae8-7059-4fff-a97e-036365916d68"),
                            CreatedAt = new DateTime(2024, 9, 17, 12, 27, 52, 706, DateTimeKind.Local).AddTicks(3896),
                            Name = "tragedy",
                            UpdatedAt = new DateTime(2024, 9, 17, 12, 27, 52, 706, DateTimeKind.Local).AddTicks(3896)
                        },
                        new
                        {
                            Id = new Guid("fe4e5fc6-1800-4218-835c-0e0ed6bb714c"),
                            CreatedAt = new DateTime(2024, 9, 17, 12, 27, 52, 706, DateTimeKind.Local).AddTicks(3897),
                            Name = "history",
                            UpdatedAt = new DateTime(2024, 9, 17, 12, 27, 52, 706, DateTimeKind.Local).AddTicks(3897)
                        });
                });

            modelBuilder.Entity("TheatricalPlayersRefactoringKata.Data.Domain.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("StatementId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("StatementId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("TheatricalPlayersRefactoringKata.Data.Domain.Performance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Audience")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("InvoiceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayId1")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("PlayId1");

                    b.ToTable("Performances");
                });

            modelBuilder.Entity("TheatricalPlayersRefactoringKata.Data.Domain.PerformanceCost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PerformanceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("StatementId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PerformanceId");

                    b.HasIndex("StatementId");

                    b.ToTable("PerformanceCost");
                });

            modelBuilder.Entity("TheatricalPlayersRefactoringKata.Data.Domain.Play", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GenreId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Lines")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Plays");
                });

            modelBuilder.Entity("TheatricalPlayersRefactoringKata.Data.Domain.Statement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Credits")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TotalCost")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Statements");
                });

            modelBuilder.Entity("TheatricalPlayersRefactoringKata.Data.Domain.Invoice", b =>
                {
                    b.HasOne("TheatricalPlayersRefactoringKata.Data.Domain.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheatricalPlayersRefactoringKata.Data.Domain.Statement", null)
                        .WithMany("Invoices")
                        .HasForeignKey("StatementId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("TheatricalPlayersRefactoringKata.Data.Domain.Performance", b =>
                {
                    b.HasOne("TheatricalPlayersRefactoringKata.Data.Domain.Invoice", null)
                        .WithMany("Performances")
                        .HasForeignKey("InvoiceId");

                    b.HasOne("TheatricalPlayersRefactoringKata.Data.Domain.Play", "Play")
                        .WithMany()
                        .HasForeignKey("PlayId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Play");
                });

            modelBuilder.Entity("TheatricalPlayersRefactoringKata.Data.Domain.PerformanceCost", b =>
                {
                    b.HasOne("TheatricalPlayersRefactoringKata.Data.Domain.Performance", "Performance")
                        .WithMany()
                        .HasForeignKey("PerformanceId");

                    b.HasOne("TheatricalPlayersRefactoringKata.Data.Domain.Statement", "Statement")
                        .WithMany("PerformanceCost")
                        .HasForeignKey("StatementId");

                    b.Navigation("Performance");

                    b.Navigation("Statement");
                });

            modelBuilder.Entity("TheatricalPlayersRefactoringKata.Data.Domain.Play", b =>
                {
                    b.HasOne("TheatricalPlayersRefactoringKata.Data.Domain.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("TheatricalPlayersRefactoringKata.Data.Domain.Statement", b =>
                {
                    b.HasOne("TheatricalPlayersRefactoringKata.Data.Domain.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("TheatricalPlayersRefactoringKata.Data.Domain.Customer", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("TheatricalPlayersRefactoringKata.Data.Domain.Invoice", b =>
                {
                    b.Navigation("Performances");
                });

            modelBuilder.Entity("TheatricalPlayersRefactoringKata.Data.Domain.Statement", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("PerformanceCost");
                });
#pragma warning restore 612, 618
        }
    }
}
